version: 2.1

orbs:
  go: circleci/go@1

jobs:
  build:
    executor:
      name: go/default
      tag: &tag '1.16'
    working_directory: ~/go/src/github.com/triggermesh/aws-custom-runtime
    steps:
      - checkout
      - run:
          name: Building package
          command: make build

  test:
    executor:
      name: go/default
      tag: *tag
    working_directory: ~/go/src/github.com/triggermesh/aws-custom-runtime
    steps:
      - checkout
      - run:
          name: Run fmt-test
          command: make fmt-test
      - run:
          name: Installing golangci-lint
          command: make install-golangci-lint
      # - run:
      #     name: Run lint
      #     command: make lint
      - run:
          name: Run test/cover
          command: make cover
          environment:
            TEST_OUTPUT_DIR: /tmp/test-results/
            COVER_OUTPUT_DIR: /tmp/cover-results/
      - store_test_results:
          path: /tmp/test-results/
      - store_artifacts:
          path: /tmp/cover-results/

  release:
    executor:
      name: go/default
      tag: *tag
    working_directory: ~/go/src/github.com/triggermesh/aws-custom-runtime
    steps:
      - checkout
      - run:
          name: Building release packages
          command: make release
          environment:
            DIST_DIR: /tmp/dist/
            CGO_ENABLED: 0
      - run:
          name: Installing github-release tool
          command: go get github.com/meterup/github-release
      - run:
          name: Creating github release
          command: |
            PRE_RELEASE=${CIRCLE_TAG/${CIRCLE_TAG%-rc[0-9]*}/}
            github-release delete -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} 2>/dev/null ||:
            ./scripts/release-notes.sh ${CIRCLE_TAG} | github-release release ${PRE_RELEASE:+-p} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} -d -

            max_tries=3
            for _ in $(seq 1 ${max_tries}); do
              github-release info -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} >/dev/null && break
              sleep 1
            done

            for f in $(find /tmp/dist -type f); do github-release upload -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} -n $(basename ${f}) -f ${f} ; done

workflows:
  build-test-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
      - test:
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
      - release:
          context: production
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
            branches:
              ignore: /.*/
